### ISSUE TITLE
Excessive pings with gRPC

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#1867]
**Problem description**
I occasionally see log messages like this:

```
2017-09-12 12:02:41,677 623945 [grpc-default-executor-14] WARN  i.p.c.stream.impl.ControllerImpl - gRPC call failed with server error: RESOURCE_EXHAUSTED: Bandwidth exhausted
HTTP/2 error code: ENHANCE_YOUR_CALM
Received Goaway
too_many_pings
```

Is this some sort of configuration issue?

**Problem location**
Controller, client and server.

**Suggestions for an improvement**
Investigate the issue.

**Comment by shrids** [comment]
Similar issue:  https://github.com/pravega/pravega/issues/1621

**Comment by shrids** [comment]
Background:
In a normal scenario the grpc keep alive configuration is for 6 mins i.e. a keep alive is sent to the controller server every 6 mins in case of outstanding rpcs. (This is greater than 5 mins configured on the server.) .The current version of grpc is 1.4.0 and post grpc version 1.3.0 the netty grpc server detects overly aggressive keepalives from clients and sends too_many_pings error to such clients.

Steps to reproduce:

- For the test used the server side `PermitKeepAliveTime `as 10 seconds. (If more than one ping is received in 10 seconds then "too_many_pings" error is sent by the grpc server)
- The client is configured with a `KeepAlivetime ` as 20 seconds. (i.e. the client will send a ping every 20 seconds.)
- Now if the GRPC server takes around 40 seconds to complete rpc call then two pings are sent by the client once every 20 seconds. Multiple iterations of this does not throw any exceptions.

```
2017-09-13 19:12:16,569 41058 [grpc-default-worker-ELG-3-2] DEBUG io.grpc.netty.NettyServerHandler - 
----------------OUTBOUND--------------------
[*id: 0x3adc925f*, L:/127.0.0.1:43741 - R:/127.0.0.1:52918] PING: ack=true, length=8, bytes=0000000000000457
```

- If the grpc server completes  `io.pravega.client.stream.impl.ControllerImpl.RPCAsyncCallback#onNext` with an unrecognized option (-1) which leads to illegalArgumentException from protobuf ; then the next invocation of the RPC call will cause a newer id to be created. Due to this pings are sent by the client for both the ids. This leads to multiple pings being sent to the server leading to a `too_many_pings` error.

This is similar to issue #1788

**Comment by shrids** [comment]
Summary: This is not a configuration issue.

Details
- In a non error scenario grpc client and sends a PING request to the server at the configured interval. (KeepAliveInterval)
- In an error scenario [ when the grpc server returns with an error `io.grpc.stub.StreamObserver.onERROR()` is invoked ] observing that multiple ping request are sent by the grpc client for a given channel id in a matter of few milliseconds.

- Do not see any errors in the code / configuration of GRPC.
- See a similar issue `https://github.com/grpc/grpc-java/issues/3274` which is fixed in GRPC version 1.6.x

**Comment by conanchen** [comment]
still have the same problem although I am using grpc 1.6.1 on Android.
10-05 21:53:22.303 17969-18142/org.ditto.sexyimage W/OkHttpClientTransport: io.grpc.okhttp.OkHttpClientTransport$ClientFrameHandler@c286347: Received GOAWAY with ENHANCE_YOUR_CALM. Debug data: too_many_pings
10-05 21:53:22.303 17969-18142/org.ditto.sexyimage W/AtomicBackoff: Increased {0} to {1}
10-05 21:53:22.308 17969-30828/org.ditto.sexyimage I/ImageManService: onError grpc service check health
                                                                      RESOURCE_EXHAUSTED: Bandwidth exhausted
                                                                      HTTP/2 error code: ENHANCE_YOUR_CALM
                                                                      Received Goaway
                                                                      too_many_pings

**Comment by bruce-sha** [comment]
+1  I am using grpc 1.13.1
