### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by RaulGracia** [pravega/pravega#2835]
**Problem description**
I found that the bottom link in this page is broken: http://pravega.io/docs/latest/streamcuts/
The broken link contains this `variable.pravega_samples_verion`, which may be a typo (should the variable be called `variable.pravega_samples_veri(s)on`?). It would be necessary to check that the rest of links that use this variable are working.

**Problem location**
Documentation.

**Suggestions for an improvement**
Fix broken links.

**Comment by Aparnarr** [comment]
The below fix is required: will edit it
(https://github.com/pravega/pravega-samples/tree/v0.3.1/pravega-client-examples/src/main/java/io/pravega/example/streamcuts)

**Comment by RaulGracia** [comment]
Thanks @Aparnarr. Before closing the issue, could you confirm that there are no other similar links broken due to the same problem?

**Comment by fpj** [comment]
If I understand it right, @Aparnarr has edited the documentation page, but I don't see a PR actually fixing the issue. Is it the case that it has been fixed in `master` and not in the `r0.3` branch?

**Comment by RaulGracia** [comment]
I think that I see what could have happened: It looks like @Aparnarr has directly edited the `streamcuts.md` file in `master`, as the link is fixed (but hardcoded to `v0.3.1`). As can be seen, the problem persists for branch `r0.3`: [clink bottom link in this page](https://github.com/pravega/pravega/blob/r0.3/documentation/src/docs/streamcuts.md). Clearly, we need to create a PR associated to this issue as documentation follows the same lifecycle as code.

**Comment by Aparnarr** [comment]
Your are right Raul : i assure that will redo according to the procedure

**Comment by RaulGracia** [comment]
This has been temporarily fixed via #2867, but we still need to make use of variables in documentation to avoid hard coded release numbers.
