### ISSUE TITLE
zookeeper logs show QuorumPeer Error closing file

### ISSUE THREAD

**Issue by Raghuveera-Rao** [pravega/pravega#3568]
Deployed
Pravega-Operator image: pravega/pravega-operator:0.3.2
Pravega build used : 0.5.0-2189.cabe11b 
Zookeeper-operator image: pravega/zookeeper-operator:0.2.1
Ran small i/o workload (Total - 4 readers, 3 writers, 120 events/sec, ~ 100 KB/sec IO)

Environment details: PKS / K8 with medium cluster:

```
3 master nodes @ large.cpu (4 CPU, 4 GB Ram, 16 GB Disk)
10 worker nodes @ xlarge.cpu(8 cpu, 8 GB Ram, 32 GB Disk)
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend 
```
See these errors in zk-0 , zk-1 and zk-2 even without restarting any zookeepers.

```
2019-04-04 09:59:37,732 [myid:1] - ERROR [ProcessThread(sid:1 cport:-1)::QuorumPeer@1564] - Error writing next dynamic config file to disk:
2019-04-04 09:59:37,736 [myid:1] - ERROR [LearnerHandler-/172.24.2.3:50172:QuorumPeer@1596] - Error closing file:
2019-04-04 09:59:37,737 [myid:1] - WARN  [LearnerHandler-/172.24.2.3:50172:QuorumPeer@1527] - Restarting Leader Election
2019-04-04 09:59:37,737 [myid:1] - INFO  [pravega-zk-0.pravega-zk-headless.default.svc.cluster.local/172.24.2.2:3888:QuorumCnxManager$Listener@892] - Leaving listener


```

[zk_logs.zip](https://github.com/pravega/pravega/files/3047471/zk_logs.zip)

**Comment by RaulGracia** [comment]
This has been fixed via https://github.com/pravega/zookeeper-operator/pull/69.

**Comment by Raghuveera-Rao** [comment]
> This has been fixed via pravega/zookeeper-operator#69.

Which build  is it fixed and is it QA testable ?

**Comment by RaulGracia** [comment]
Yes, as soon as the new Zookeeper image with the fix is updated in https://hub.docker.com/r/pravega/zookeeper, it will be easy to validate. @pbelgundi may know the status of publishing the new Zookeeper image in that repo.

**Comment by Raghuveera-Rao** [comment]
I tried with this :
```
bookkeeper:0.5.0-2291.3ccff63
pravega:0.5.0-2291.3ccff63
zookeeper:3.5.4-beta-operator
pravega/pravega-operator:0.3.2
pravega/zookeeper-operator:0.2.3
```

Used the **zookeeper-operator:0.2.3**

I am still seeing this error:
```
2019-07-02 12:07:14,952 [myid:1] - INFO  [QuorumPeer[myid=1](plain=/0.0.0.0:2181)(secure=disabled):ZooKeeperServer@160] - Created server with tickTime 2000 minSessionTimeout 4000 maxSessionTimeout 40000 datadir /data/version-2 snapdir /data/version-2
2019-07-02 12:07:14,953 [myid:1] - INFO  [QuorumPeer[myid=1](plain=/0.0.0.0:2181)(secure=disabled):Leader@432] - LEADING - LEADER ELECTION TOOK - 64 MS
2019-07-02 12:07:14,955 [myid:1] - INFO  [QuorumPeer[myid=1](plain=/0.0.0.0:2181)(secure=disabled):FileTxnSnapLog@367] - Snapshotting: 0x0 to /data/version-2/snapshot.0
2019-07-02 12:07:15,254 [myid:1] - ERROR [QuorumPeer[myid=1](plain=/0.0.0.0:2181)(secure=disabled):QuorumPeer@1564] - Error writing next dynamic config file to disk:
2019-07-02 12:07:15,613 [myid:1] - INFO  [QuorumPeer[myid=1](plain=/0.0.0.0:2181)(secure=disabled):Leader@1264] - Have quorum of supporters, sids: [ [1],[1] ]; starting up and setting last processed zxid: 0x100000000
2019-07-02 12:07:15,614 [myid:1] - ERROR [QuorumPeer[myid=1](plain=/0.0.0.0:2181)(secure=disabled):QuorumPeer@1596] - Error closing file:
2019-07-02 12:07:15,620 [myid:1] - INFO  [QuorumPeer[myid=1](plain=/0.0.0.0:2181)(secure=disabled):CommitProcessor@255] - Configuring CommitProcessor with 1 worker threads.
```

**Comment by Raghuveera-Rao** [comment]
[pravega-k8s-logging-2019-07-02-08-54-07 (2).zip](https://github.com/pravega/pravega/files/3350116/pravega-k8s-logging-2019-07-02-08-54-07.2.zip)

**Comment by RaulGracia** [comment]
Yes, because you have not tests the right changes. The changes are in the "Zookeeper image", but you are still using the old one (`zookeeper:3.5.4-beta-operator`). Please, use at the moment the Zookeeper image `pbelgundi/zookeeper:22.0` to validate this issue.

**Comment by Raghuveera-Rao** [comment]
@RaulGracia  thanks for the zk supported image.
Build-
```
bookkeeper:0.5.0-2291.3ccff63
pravega:0.5.0-2291.3ccff63
pbelgundi/zookeeper:22.0
pravega/pravega-operator:0.3.2
pravega/zookeeper-operator:0.2.3
```
I am **not** seeing 'Error writing next dynamic config file to disk'

However, I am seeing this error 
`ERROR [LearnerHandler-/172.24.27.6:55242:LearnerHandler@624] - Unexpected exception causing shutdown while sock still open
`

**Comment by RaulGracia** [comment]
When you created the Zookeeper cluster, have you made sure that the PVCs of any previous deployment were cleaned?

**Comment by Raghuveera-Rao** [comment]
Yes.. all pvc were deleted.. 
$ kubectl get pvc 
```
NAME                                    STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
cache-pravega-pravega-segmentstore-0    Bound    pvc-603b878f-9ccd-11e9-aede-005056ba320d   30Gi       RWO            standard       26m
cache-pravega-pravega-segmentstore-1    Bound    pvc-88daf068-9ccd-11e9-aede-005056ba320d   30Gi       RWO            standard       25m
cache-pravega-pravega-segmentstore-2    Bound    pvc-9cd13017-9ccd-11e9-aede-005056ba320d   30Gi       RWO            standard       24m
data-pravega-zk-0                       Bound    pvc-e649cf07-9ccc-11e9-aede-005056ba320d   20Gi       RWO            standard       29m
data-pravega-zk-1                       Bound    pvc-00bb9f5f-9ccd-11e9-aede-005056ba320d   20Gi       RWO            standard       29m
data-pravega-zk-2                       Bound    pvc-1686f582-9ccd-11e9-aede-005056ba320d   20Gi       RWO            standard       28m
index-pravega-bookie-0                  Bound    pvc-60006dc1-9ccd-11e9-aede-005056ba320d   10Gi       RWO            standard       26m
index-pravega-bookie-1                  Bound    pvc-60096fd1-9ccd-11e9-aede-005056ba320d   10Gi       RWO            standard       26m
index-pravega-bookie-2                  Bound    pvc-601c4e9d-9ccd-11e9-aede-005056ba320d   10Gi       RWO            standard       26m
index-pravega-bookie-3                  Bound    pvc-602b82f0-9ccd-11e9-aede-005056ba320d   10Gi       RWO            standard       26m
journal-pravega-bookie-0                Bound    pvc-5ffc7aed-9ccd-11e9-aede-005056ba320d   100Gi      RWO            standard       26m
journal-pravega-bookie-1                Bound    pvc-600dd9b4-9ccd-11e9-aede-005056ba320d   100Gi      RWO            standard       26m
journal-pravega-bookie-2                Bound    pvc-6013e6a4-9ccd-11e9-aede-005056ba320d   100Gi      RWO            standard       26m
journal-pravega-bookie-3                Bound    pvc-602e30fe-9ccd-11e9-aede-005056ba320d   100Gi      RWO            standard       26m
ledger-pravega-bookie-0                 Bound    pvc-5ffe34d0-9ccd-11e9-aede-005056ba320d   100Gi      RWO            standard       26m
ledger-pravega-bookie-1                 Bound    pvc-600563c9-9ccd-11e9-aede-005056ba320d   100Gi      RWO            standard       26m
ledger-pravega-bookie-2                 Bound    pvc-60178a4e-9ccd-11e9-aede-005056ba320d   100Gi      RWO            standard       26m
ledger-pravega-bookie-3                 Bound    pvc-60284144-9ccd-11e9-aede-005056ba320d   100Gi      RWO            standard       26m
pravega-tier2                           Bound    pvc-575fabf9-9ccd-11e9-aede-005056ba320d   2000Gi     RWX            nfs            26m
pvc-shaka-zulu-nfs-client-provisioner   Bound    pv-shaka-zulu-nfs-client-provisioner       10Mi       RWO                           27m

```

**Comment by fpj** [comment]
Out of context, this is not a problem:

```
ERROR [LearnerHandler-/172.24.27.6:55242:LearnerHandler@624] - Unexpected exception causing shutdown while sock still open
```

to be a problem, I need to know that there is no leader with a quorum of supporters.

**Comment by Raghuveera-Rao** [comment]
I am not seeing 'ERROR [QuorumPeer' error now with the above mentioned zk versions..

**Comment by pbelgundi** [comment]
There are no changes to zookeeper-operator image. 
Changes are in zookeeper image.

This needs to be tested with zookeeper image : 
pravega/zookeeper:0.2.2 OR 
pravega/zookeeper:latest  

I have pushed these updated images to docker hub.

**Comment by Raghuveera-Rao** [comment]
> There are no changes to zookeeper-operator image.
> Changes are in zookeeper image.
> This needs to be tested with zookeeper image :
> pravega/zookeeper:0.2.2 OR
> pravega/zookeeper:latest
> I have pushed these updated images to docker hub.

You meant to use **pbelgundi/zookeeper:22.0** for zk image ?

**Comment by pbelgundi** [comment]
> > There are no changes to zookeeper-operator image.
> > Changes are in zookeeper image.
> > This needs to be tested with zookeeper image :
> > pravega/zookeeper:0.2.2 OR
> > pravega/zookeeper:latest
> > I have pushed these updated images to docker hub.
> 
> You meant to use **pbelgundi/zookeeper:22.0** for zk image ?

Nope. Please use pravega/zookeeper:0.2.2 OR pravega/zookeeper:latest
I have updated both these images yesterday, so they have the fix.

**Comment by fpj** [comment]
@pbelgundi @Raghuveera-Rao I don't see where this conversation is going. It started with an error to write to a file, and now it became about an error message that out of context is meaningless. If there is no real issue being discussed, please close it.

**Comment by Raghuveera-Rao** [comment]
There was confusion with zookeeper operator image and zk image...
Have to use 
```
image:
    repository: "pravega/zookeeper"
    tag: "0.2.2"
    pullPolicy: Always

```
this in zk.yaml mainfest file.
There is no change in zk-operator

**Comment by Raghuveera-Rao** [comment]
> @pbelgundi @Raghuveera-Rao I don't see where this conversation is going. It started with an error to write to a file, and now it became about an error message that out of context is meaningless. If there is no real issue being discussed, please close it.

Will close this if ''ERROR [QuorumPeer' error comes with this ..
